# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

  - stage: Build
    jobs:
      - job: 'Job_Build'
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

  - stage: Test
    dependsOn: Build
    jobs:
      - job: 'Job_Test'
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            testRunTitle: 'JUnit tests'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: true
            sqMavenPluginVersionChoice: 'pom'


  - stage: AgentTasks
    dependsOn: Test
    jobs:
      - job: 'Job_AgentTasks'
        steps:
        - task: ServiceNow-DevOps-Build-Sonar-Registration@1
          inputs:
            connectedServiceName: 'demo'
            sonarProjectKey: 'pramaraju96_ServiceNow-DevOps-Change-Sample'
            sonarInstanceUrl: 'https://sonarcloud.io'

        - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
          inputs:
            connectedServiceName: 'demo'
            artifactsPayload: |
              {
                "artifacts": [
                    {
                      "name": "agent-artifact-alpha",
                      "version": "1.$(Build.BuildId)",
                      "semanticVersion": "1.$(Build.BuildId).0",
                      "repositoryName": "DevOps CI Sample"
                    }
                ]
              }
        - task: ServiceNow-DevOps-Agent-Package-Registration@1
          inputs:
            connectedServiceName: 'demo'
            packageName: 'app-devops-change-velocity'
            artifactsPayload: |
              {
                  "artifacts": [
                  {
                      "name": "agent-artifact-alpha",
                      "repositoryName": "DevOps CI Sample",
                      "version": "1.$(build.buildId)",
                      "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                      "taskExecutionNumber":"$(build.buildId)",
                      "stageName":"$(system.jobDisplayName)",
                      "branchName":"$(build.sourceBranchName)"
                  }],
                  "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                  "taskExecutionNumber":"$(build.buildId)",
                  "stageName":"$(system.jobDisplayName)",
                  "branchName":"$(build.sourceBranchName)"
              }

  - stage: ServerTasks
    dependsOn: AgentTasks
    jobs:
      - job: 'Job_ServerTasks'
        pool: server
        steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'demo'
            UpstreamJob: 'Job_AgentTasks'
            changeRequestDetails: |
              {
              "autoCloseChange":true,
              "attributes":{
              "assignment_group":{
              "name":"Change Management"
              },
              "chg_model":{
              "name":"Normal"
              },
              "category":"DevOps",
              "priority":"2",
              "comments":"This is a sample pipeline comment to be added to the change",
              "work_notes":"This is a sample pipeline work_notes to be added to the change"
              }
              }